# Generated by Django 5.0.7 on 2025-03-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_answer_question_alter_question_quiz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='selected_answer',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer_text',
            field=models.TextField(default='Not answered'),
        ),
    ]
