# Generated by Django 5.0.7 on 2025-03-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_useranswer_selected_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
